services:
  postgres_db:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password.123
      POSTGRES_DB: DigitalECommerceDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecommerce_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Password123*
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
  
volumes:
  postgres_data: